
package number.msisdn.soapclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "TransportService", targetNamespace = "http://och.dk/server/services/ich", wsdlLocation = "https://test02services.och.dk/v1/Transport?wsdl")
public class TransportService
    extends Service
{

    private final static URL TRANSPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRANSPORTSERVICE_EXCEPTION;
    private final static QName TRANSPORTSERVICE_QNAME = new QName("http://och.dk/server/services/ich", "TransportService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://test02services.och.dk/v1/Transport?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANSPORTSERVICE_WSDL_LOCATION = url;
        TRANSPORTSERVICE_EXCEPTION = e;
    }

    public TransportService() {
        super(__getWsdlLocation(), TRANSPORTSERVICE_QNAME);
    }

    public TransportService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSPORTSERVICE_QNAME, features);
    }

    public TransportService(URL wsdlLocation) {
        super(wsdlLocation, TRANSPORTSERVICE_QNAME);
    }

    public TransportService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSPORTSERVICE_QNAME, features);
    }

    public TransportService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransportService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Transport
     */
    @WebEndpoint(name = "TransportPort")
    public Transport getTransportPort() {
        return super.getPort(new QName("http://och.dk/server/services/ich", "TransportPort"), Transport.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Transport
     */
    @WebEndpoint(name = "TransportPort")
    public Transport getTransportPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://och.dk/server/services/ich", "TransportPort"), Transport.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSPORTSERVICE_EXCEPTION!= null) {
            throw TRANSPORTSERVICE_EXCEPTION;
        }
        return TRANSPORTSERVICE_WSDL_LOCATION;
    }

}
