
package number.msisdn.soapclient;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Transport", targetNamespace = "http://och.dk/server/services/ich")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Transport {


    /**
     * 
     * @param batch
     * @return
     *     returns boolean
     * @throws UnavailableException_Exception
     * @throws UserException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "send", targetNamespace = "http://och.dk/server/services/ich", className = "number.msisdn.soapclient.Send")
    @ResponseWrapper(localName = "sendResponse", targetNamespace = "http://och.dk/server/services/ich", className = "number.msisdn.soapclient.SendResponse")
    public boolean send(
        @WebParam(name = "batch", targetNamespace = "")
        Batch batch)
        throws UnavailableException_Exception, UserException_Exception
    ;

    /**
     * 
     * @param confirmBatchId
     * @return
     *     returns number.msisdn.soapclient.Batch
     * @throws UnavailableException_Exception
     * @throws UserException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "receive", targetNamespace = "http://och.dk/server/services/ich", className = "number.msisdn.soapclient.Receive")
    @ResponseWrapper(localName = "receiveResponse", targetNamespace = "http://och.dk/server/services/ich", className = "number.msisdn.soapclient.ReceiveResponse")
    public Batch receive(
        @WebParam(name = "confirmBatchId", targetNamespace = "")
        long confirmBatchId)
        throws UnavailableException_Exception, UserException_Exception
    ;

    /**
     * 
     * @param batchId
     * @return
     *     returns boolean
     * @throws UnavailableException_Exception
     * @throws UserException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirm", targetNamespace = "http://och.dk/server/services/ich", className = "number.msisdn.soapclient.Confirm")
    @ResponseWrapper(localName = "confirmResponse", targetNamespace = "http://och.dk/server/services/ich", className = "number.msisdn.soapclient.ConfirmResponse")
    public boolean confirm(
        @WebParam(name = "batchId", targetNamespace = "")
        long batchId)
        throws UnavailableException_Exception, UserException_Exception
    ;

}
